### ISSUE TITLE
Preserve first line indentation

### ISSUE THREAD

**Issue by dy** [miguelmota/fnbody#1]
Hi!
I use fnbody in [audio-lab](https://github.com/dfcreative/audio-lab), where I change code of the function generating a sound, and face the issue that fnbody erases the indentation of the first line, which is quite annoying thing.
What is the reason behind that? Maybe it is better to keep user’s formatting of function body?

**Comment by miguelmota** [comment]
Maybe I should use `.trimRight()`?

**Comment by miguelmota** [comment]
Good point, I updated it to preserve leading and ending whitespace.

The reason for the trimming was because I was grabbing the function body, modifying it, and invoking it, and the whitespace was irrelevant.

Thanks!
